import "./globals.css";
import { Prompt } from 'next/font/google'
import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";

const prompt = Prompt({
  weight: ['400','700'], // if single weight, otherwise you use array like [400, 500, 700],
  style: 'normal', // if single style, otherwise you use array like ['normal', 'italic']
  subsets: ['latin'],
})
export const metadata = {
  title: "Visit Phetchabun",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={prompt.className}>
      <Navbar/>
      {children}
      </body>
    </html>
  );
}
